name: Bangun DLL untuk Arbitrase

on:
  workflow_dispatch:
  push:
    branches: [ utama ]  # Ganti ke 'main' jika nama branch-mu bukan 'utama'

jobs:
  membangun-dll:
    runs-on: windows-latest

    steps:
      - name: Checkout Kode
        uses: actions/checkout@v4

      - name: Setup Visual Studio Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build DLL
        run: |
          cl /LD arbitrase_berbagi_memori.cpp arbitrase_berbagi_memori.def /Fe:arbitrase_shared_memory.dll

      - name: Upload DLL sebagai Artifact
        uses: actions/upload-artifact@v4
        with:
          name: arbitrase_shared_memory
          path: arbitrase_shared_memory.dll
